### ISSUE TITLE
File name 'parser.py' can create problems

### ISSUE THREAD

**Issue by ZilH** [xmsley614/nt_tool#2]
When I was trying to run the main.py, it raises a bug saying

`Traceback (most recent call last):
  File "xxx\nt_tool\main_zh.py", line 3, in <module>
    from parser import convert_response, results_to_excel
ImportError: cannot import name 'convert_response' from 'parser' (unknown location)`

https://stackoverflow.com/questions/58585690/python-cannot-import-unknown-location

it seems "parser" is a library in python. I renamed the "parser" to "parserNT" and then the problem was solved.

Maybe it is a good idea to change the name 'parser' to something like 'utils'?

**Comment by xmsley614** [comment]
Thanks. I have fixed this.
