### ISSUE TITLE
any other skyteam airlines?

### ISSUE THREAD

**Issue by sgupta-taekus** [xmsley614/nt_tool#23]
are there any other skyteam airlines being integrated? specifically aeromexico, korean air, air france

**Comment by sgupta-taekus** [comment]
also, how did you know to use https://api.delta.com/mwsb/service/shop? I'm trying to potentially do something similar for Virgin Atlantic since Delta/VA are almost identical

**Comment by xmsley614** [comment]
You can catch the request throught ios or andriod device.

**Comment by sgupta-taekus** [comment]
It looks like Delta's API is now down. Do you have any other SkyTeam API's? Virgin Atlantic would be the most helpful... i tried to catch the requests through iOS but those API's didn't work. I'm probably doing something wrong.

<img width="717" alt="image" src="https://github.com/xmsley614/nt_tool/assets/127056667/a46b3052-7703-43b6-bb2c-2407d123bdca">
