### ISSUE TITLE
Expression of type "list[Unknown]" cannot be assigned to return type "dict[Unknown, Unknown]"   "list[Unknown]" is incompatible with "dict[Unknown, Unknown]"

### ISSUE THREAD

**Issue by davidlin158** [xmsley614/nt_tool#5]
`v1 = {**v1, **segs_single, **prices_single}
            results.append(v1)
        return results`
Error message when using this return results

**Comment by xmsley614** [comment]
what's your version of python?

**Comment by davidlin158** [comment]
tried 3.9 in anaconda and 3.10 they all have this problem. also in the end:
`    sf.to_excel('output.xlsx').save()
    `

**Comment by xmsley614** [comment]
Can't figure it out. Dose someone else also have this problem?
Or maybe you can pull the newest commit and try to run web.py.

**Comment by xmsley614** [comment]
I happened to figure it out.
What IDE are you using?
You can replace "list" with "List"， and add an import which is "from typing import List". 
That shall solve the problem.
